### ISSUE TITLE
InsufficientDataException on perfect agreement with one label

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-statistics#24]
Sometimes (but unfortunately very rarely in reality) there might be a perfect agreement among annotators, such as:

```java
@Test
	public void testPerfectAgreementTwoCategories()
			throws Exception
	{
		CodingAnnotationStudy study = new CodingAnnotationStudy(3);
		study.addItem("high", "high", "high");
		study.addItem("low", "low", "low");

		FleissKappaAgreement pi = new FleissKappaAgreement(study);
		double agreement = pi.calculateAgreement();
		assertEquals(1.00, agreement, 0.001);
	}
```

There were two labels, all agreed -> 1.0 Fleiss Kappa/Pi

However, in this similar case, InsufficientDataException is thrown:

```java
	@Test
	public void testPerfectAgreementOneCategory()
			throws Exception
	{
		CodingAnnotationStudy study = new CodingAnnotationStudy(3);
		study.addItem("high", "high", "high");
		study.addItem("high", "high", "high");

		FleissKappaAgreement pi = new FleissKappaAgreement(study);
		double agreement = pi.calculateAgreement();
		assertEquals(1.00, agreement, 0.001);
	}
```

org.dkpro.statistics.agreement.InsufficientDataException: An annotation study needs at least two different categories; otherwise there is no decision for the raters to agree on.

Would be meaningful to inform the CodingAnnotationStudy that there are more than one possible category?

**Comment by chmeyer** [comment]
There's a method AnnotationStudy.addCategory, which was intended for that. Thus, for ex. 2, try addCategory("low") -> hopefully this works and there isn't any issue :)

**Comment by habernal** [comment]
This gives even more interesting results :)

```java
@Test
	public void testPerfectAgreementOneCategory()
			throws Exception
	{
		CodingAnnotationStudy study = new CodingAnnotationStudy(3);
		study.addItem("high", "high", "high");
		study.addItem("high", "high", "high");

		study.addCategory("low");

		FleissKappaAgreement pi = new FleissKappaAgreement(study);
		double agreement = pi.calculateAgreement();
		assertEquals(1.00, agreement, 0.001);
	}
```

org.dkpro.statistics.agreement.InsufficientDataException: Insufficient variation. Most likely, the raters only used a single category which yields an expected agreement of 1.0. In this case, it is not possible to make any statement about the other categories and thus the agreement of the study itself.

**Comment by chmeyer** [comment]
Right. Actually, it works as expected! Remember that the denominator is 1 - A_E yielding 0 in this case. If there is only one category used by the annotators, agreement is undefined rather than perfect. The main reason is that if there's practically no decision to which could be used to construct a noise model from. In many cases, I think it is difficult to claim perfect agreement for a study using only a single label -> a machine always pressing the same button could reproduce it...

Adding empty categories makes sense, however, in a more realistic setting with many categories and items. Consider:

	        CodingAnnotationStudy study = new CodingAnnotationStudy(3);
	        study.addItem("high", "high", "high");
	        study.addItem("mid", "mid", "mid");

	        FleissKappaAgreement pi = new FleissKappaAgreement(study);
	        System.out.println(pi.calculateAgreement());
	        System.out.println("AO " + pi.calculateObservedAgreement());
	        System.out.println("AE " + pi.calculateExpectedAgreement());

	        RandolphKappaAgreement r = new RandolphKappaAgreement(study);
	        System.out.println(r.calculateAgreement());
	        System.out.println("AO " + r.calculateObservedAgreement());
	        System.out.println("AE " + r.calculateExpectedAgreement());

	        KrippendorffAlphaAgreement a = new KrippendorffAlphaAgreement(study, new NominalDistanceFunction());
	        System.out.println(a.calculateAgreement());
	        System.out.println("DO " + a.calculateObservedDisagreement());
	        System.out.println("DE " + a.calculateExpectedDisagreement());

When adding

	        study.addCategory("low");

the expected agreement of the r mesaure will change, but not the overall agreement, since we have 1-AE / 1-AE = 1. It is thus just an indicator of the noise model.

When adding

	        study.addItem("mid", "mid", "high");

you will note that the S measure will also change its overall score. For the other measures, empty categories do not influence the score (grounded in the measure definition). This again boils down to unused categories yielding undefined agreement. Try:

	        for (Object category : study.getCategories())
	        	System.out.println(category + ": " + a.calculateCategoryAgreement(category));

Please reopen if questions remain.
