### ISSUE TITLE
Unitizing study clarification 

### ISSUE THREAD

**Issue by lfoppiano** [dkpro/dkpro-statistics#28]
Hi, 
     I'm trying to generate annotations for a sequence labeling exercise in order to extract AAI measures. I have several files of documents where annotators has selected part of the text and tagged it as such. 

Something like `This is a text with an <blabla>important</blabla> item`. 

At the annotation level I have used the `CodingAnnotationStudy` and I've just extracted each token from each file and aggregate them in a list of Items. 
The output would be by token (normalised along all the annotators) having the assigned label to each token and this could have been generated for each annotated files.

I then realised that this such task is more likely a Unitize Study instead where annotators can give different span along the same continuous. 
When looking for the `UnitizingAnnotationStudy` I realised that it requires a length of the continuous and (eventually) some start/end offsets. How that can be used over several files? Should I think these files as a single stream and normalise the offsets to work on that? 
Or should I create several `UnitizingAnnotationStudy` for each file and afterwards combine the study (is there a way?) or compute the resulting metrics (e.g. calculating average, etc...)? 

Thank you, I'm not sure I explained well

**Comment by reckart** [comment]
@chmeyer can probably provide a better founded answer to this, but here is what I did when faced with a similar problem: I passed once over the input documents and calculated their concatenated length because when constructing the study, I had to specify that length. I had tried before simply specifying MAX_INT as the study size to avoid having to pass over the data twice, but that makes the results go completely bogus. In the second pass, I use the offsets of the annotations in the document plus an offset calculated from all previously seen documents. So effectively, I map all documents and annotations sequentially into a single coordinate space. When you calculate the length and annotation positions, you need to consider whether you do that in terms of character offsets or in terms of token positions. Depending on your task one or the other may be more appropriate. I didn't try averaging over individual studies, but in principle that sounds like a reasonable approach as well, in particular if your documents all have a similar size. If you have very large and very small documents in your data set, it might not be the best approach unless you use a weighted average.

**Comment by lfoppiano** [comment]
@chmeyer any comment on this?

**Comment by chmeyer** [comment]
Apologies for late response.

1. The length of the continuum must be chosen according to the length of the subject being studied. Leaving the length undefined or setting it to infinity or something similar will not yield reasonable results.

2. Units can be defined on different levels, especially character- and token-level are typically reasonable. The decision best depends on what the annotators could select and/or what the task expects. For most tasks - most likely including the once presented above - token will be fine.

3. For defining the continuum in multi-document use cases, we can indeed either study each document in isolation and then average or concatenate the documents and study it as a whole. The resulting figures will likely be different, predominantly depending on the densitiy of annotations (i.e., if it is likely that each token is part of an annotation or if annotations are rare). If the individual documents belong to one overall discourse (e.g., a book dvided into multiple chapters), I suggest the concatenated version. If the documents are much different from each other, rather prefer the individual analyses. If the documents are very short (e.g., tweets), the concatenated version might be better to foster robustness. If the documents have very unequal lengths, both variants might be beneficial, as averaging the document-wise scores weigh the documents equally whereas the concatenated variant puts more weight on longer documents, The discussion is a bit similar to macro vs micro average.

**Comment by lfoppiano** [comment]
Thanks for the answer. We can close this issue.
